//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.ServiceVelib {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinates", Namespace="http://schemas.datacontract.org/2004/07/VelibLibrairy")]
    [System.SerializableAttribute()]
    public partial class Coordinates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LattitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Lattitude {
            get {
                return this.LattitudeField;
            }
            set {
                if ((this.LattitudeField.Equals(value) != true)) {
                    this.LattitudeField = value;
                    this.RaisePropertyChanged("Lattitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVelib.IVelibService")]
    public interface IVelibService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/CalculTrajectory", ReplyAction="http://tempuri.org/IVelibService/CalculTrajectoryResponse")]
        long CalculTrajectory(ServiceClient.ServiceVelib.Coordinates departure, ServiceClient.ServiceVelib.Coordinates destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/CalculTrajectory", ReplyAction="http://tempuri.org/IVelibService/CalculTrajectoryResponse")]
        System.Threading.Tasks.Task<long> CalculTrajectoryAsync(ServiceClient.ServiceVelib.Coordinates departure, ServiceClient.ServiceVelib.Coordinates destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/HelloWorld", ReplyAction="http://tempuri.org/IVelibService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/HelloWorld", ReplyAction="http://tempuri.org/IVelibService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetInstructionsTrajectory", ReplyAction="http://tempuri.org/IVelibService/GetInstructionsTrajectoryResponse")]
        string[] GetInstructionsTrajectory(ServiceClient.ServiceVelib.Coordinates depart, ServiceClient.ServiceVelib.Coordinates destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetInstructionsTrajectory", ReplyAction="http://tempuri.org/IVelibService/GetInstructionsTrajectoryResponse")]
        System.Threading.Tasks.Task<string[]> GetInstructionsTrajectoryAsync(ServiceClient.ServiceVelib.Coordinates depart, ServiceClient.ServiceVelib.Coordinates destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : ServiceClient.ServiceVelib.IVelibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.ClientBase<ServiceClient.ServiceVelib.IVelibService>, ServiceClient.ServiceVelib.IVelibService {
        
        public VelibServiceClient() {
        }
        
        public VelibServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CalculTrajectory(ServiceClient.ServiceVelib.Coordinates departure, ServiceClient.ServiceVelib.Coordinates destination) {
            return base.Channel.CalculTrajectory(departure, destination);
        }
        
        public System.Threading.Tasks.Task<long> CalculTrajectoryAsync(ServiceClient.ServiceVelib.Coordinates departure, ServiceClient.ServiceVelib.Coordinates destination) {
            return base.Channel.CalculTrajectoryAsync(departure, destination);
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string[] GetInstructionsTrajectory(ServiceClient.ServiceVelib.Coordinates depart, ServiceClient.ServiceVelib.Coordinates destination) {
            return base.Channel.GetInstructionsTrajectory(depart, destination);
        }
        
        public System.Threading.Tasks.Task<string[]> GetInstructionsTrajectoryAsync(ServiceClient.ServiceVelib.Coordinates depart, ServiceClient.ServiceVelib.Coordinates destination) {
            return base.Channel.GetInstructionsTrajectoryAsync(depart, destination);
        }
    }
}
